site/pages/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('pricing/', views.prices, name='prices'),
    path(
        'docs/',
        include(([
            path('', views.docs.index, name='index'),
        ], 'docs'), namespace='docs'),
    ),
    path(
        'terms-and-conditions/',
        views.terms_and_conditions,
        name='terms_and_conditions'
    ),
]

site/templates/partials/_bootstrap_form.html
<form method="POST">
  {% csrf_token %}
  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
  {% endfor %}
  {% for field in form.visible_fields %}
    <div class="form-group mb-4">
      {{ field.label_tag }}
      {{ field }}
    </div>
  {% endfor %}
  <button type="submit" class="btn btn--primary">Submit</button>
</form>

site/templates/partials/_messages.html
{% if messages %}
  <section class="messages">
    {% for message in messages %}
      <div class="message message--{{ message.tags }}">
          <span>{{ message }}</span>
      </div>
    {% endfor %}
  </section>
{% endif %}

site/templates/partials/_navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand navbar__logo" href="/">
      {% include 'svg/logo.svg' %}
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a
              class="nav-link {% if 'sites' in request.path %}active{% endif %}"
              href="{% url 'sites-dashboard' %}"
            >
              Sites
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if 'benchmark' in request.path %}active{% endif %}" href="{% url 'new_benchmark' %}">Benchmark</a>
          </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link {% if 'docs' in request.path %}active{% endif %}" href="{% url 'docs:index' %}">Docs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if 'pricing' in request.path %}active{% endif %}" href="{% url 'prices' %}">Pricing</a>
        </li>
      </ul>
      <ul class="navbar-nav justify-content-end">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}?next={% url 'sites-dashboard' %}">
            Login
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

site/templates/partials/_recaptcha.html
<script
  src="https://www.google.com/recaptcha/api.js?render={{ recaptcha_site_key }}"
></script>
<script>
  grecaptcha.ready(function () {
    grecaptcha
      .execute("{{ recaptcha_site_key }}", { action: "{{ recaptcha_action }}" })
      .then(function (token) {
        document.getElementById("g-recaptcha-response").value = token;
      });
  });
</script>